### ISSUE TITLE
Sandbox injection bug

### ISSUE THREAD

**Issue by AliusDieMorietur** [HowProgrammingWorks/NodejsStarterKit#148]
Wrong object assigned, probably object from config was taken instead of the necessary object. 
Problem in this [line](https://github.com/HowProgrammingWorks/NodejsStarterKit/blob/462b9cdb23130fbd2dbb300606bc2591cf8bcb2f/domain/resmon.js#L13)
![image](https://user-images.githubusercontent.com/44651557/84828922-846e6400-b02f-11ea-8b29-2ad4143201c2.png)

**Comment by tshemsedinov** [comment]
Thanks @AliusDieMorietur
