### ISSUE TITLE
Write separate logs for each thread

### ISSUE THREAD

**Issue by tshemsedinov** [HowProgrammingWorks/NodejsStarterKit#20]
Write logs to separate folder where each thread will create separate file with thread id in name.

**Comment by ArturJS** [comment]
@tshemsedinov Thanks for this great repo!
Just out of curiosity, I have a question.
[Here](https://github.com/HowProgrammingWorks/NodejsStarterKit/commit/d35a2e9c550a3c1f6bbbadca493b9a9e3552cda3#diff-212f63e53d7aa8ed04659d1cabd48137R20) you opted to write logs into a corresponding logfile, but from point of [12 factor apps](https://12factor.net/logs) application shouldn't attempt to write or manage logfiles.
```
A twelve-factor app never concerns itself with routing or storage of its output stream. It should not attempt to write to or manage logfiles. Instead, each running process writes its event stream, unbuffered, to stdout. During local development, the developer will view this stream in the foreground of their terminal to observe the app’s behavior.
```
So, why here logfiles are gonna be better than writing logs into a regular `stdout`?

**Comment by tshemsedinov** [comment]
This starter kit follows different methodology, not 12 factor, @ArturJS

**Comment by tshemsedinov** [comment]
Metaserverless methodology: stateful, containerless, no dependencies, serve from memory, minimize I/O, isolate sessions, scale with threads, don't use environment variables, don't use dependencies and a few more. @ArturJS
